all:
	javac Client.java Global.java HttpMessage.java HttpMessageReader.java HttpMessageWriter.java NetNinny.java ServerThread.java

clean:
	rm Client.class Global.class HttpMessage.class HttpMessageReader.class HttpMessageWriter.class NetNinny.class ServerThread.class

